### ISSUE TITLE
Feedback on first submission

### ISSUE THREAD

**Issue by Anisha7** [mhinojosa24/core-data-structures#1]
Good job on completing the first submission. Here’s what you can do to improve:
- Palindrome’s recursive implementation does not pass all of the tests. You’re halfway there! Try to make good use of print statements and testing to debug your code. 
- Refactor your strings code to avoid duplicate code. Look for code that is common between your three functions and try to divide it up in helper functions OR call one of the functions in the other two, such that there is no duplicate code in your file.
- Add a couple more unit tests for thoroughly testing edge cases for string challenges. Use Alan’s provided unit tests as a reference to add a couple more assert statements with function calls that use some edge case inputs.
- I see that you annotated your string functions with time complexity. Try to do this for space complexity as well. (How much space is your function using? Are you allocating any arrays/dictionaries/or big data sets? How big?)

**Comment by mhinojosa24** [comment]
Thanks for your feedback. I added time and space complexity, fixed my logic and refactored code for readability. I found this very helpful. I over thought about the logic which made me recognize an easier approach of fixing this issue. Thanks again.

**Comment by Anisha7** [comment]
Good job on making the improvements. I see that you refactored code such that there are no duplicated between find_index and find_all_indexes. However, the code for your helper function and contains function looks very similar. Is there a way to refactor your contains function as well?
