### ISSUE TITLE
Feedback: Second Challenge Submission

### ISSUE THREAD

**Issue by anselb** [mhinojosa24/core-data-structures#2]
- Your stack and queue classes look good. I highly recommend annotating the time complexity as I've noticed some people are messing those up.
- In your Set, watch out for un-optimizing code. Wherever you're checking if an item is in a set, you are moving it from a hash table into a list and looking into the list (O(n) complexity worst case). You can just use a method on your hash table to see if the item is in the set (close to, if not, O(1) complexity).
- In your Set, I think you might have misinterpreted using the hash tables size property. Set still needs its own size method, but the challenge specified doing something like [this](https://stackoverflow.com/questions/17330160/how-does-the-property-decorator-work) with `@property`. Your Set tests are great; they test strings and integers, and there is a lot of them.

**Comment by mhinojosa24** [comment]
Refactored Set class methods and this class has its own variable of size. Methods now checks if an item is in a linked list rather than a hash table. Although, I didn't quite understand @property or how I would implement it in my Set class.
