### ISSUE TITLE
Feedback: Linked Lists, Stacks & Queues

### ISSUE THREAD

**Issue by anselb** [mhinojosa24/core-data-structures#5]
- Your linked list methods look good. I recommend adding some comments in `insert_at_index` or `replace`, and I highly recommend going through and annotating your methods.
- While most of your stacks and queues implementation are good, ArrayStack is inefficient. You are correct that inserting an item an index 0 (line 80) is O(n), due to the shift in items, but popping at index 0 is not O(1) because the items have to shift back by one index. To get both from O(n) to O(1), push and pop the ArrayStack at the end of the list. Your dequeue in ArrayQueue is very similar to the pop in ArrayStack, but your ArrayQueue dequeue is correctly annotated as O(n); however, your ArrayQueue enqueue annotation is partially incorrect. While it is O(n) runtime to double an array's size and allocate that space, most of the time you are appending (O(1) runtime), so it average out to about O(1) runtime.

**Comment by mhinojosa24** [comment]
Thanks for your feedback, I updated my LinkedList, Stack, and Queue classes. I also updated the correct annotation of time complexity. Thank you once again :)
