### ISSUE TITLE
Feedback: Trees & Tree Traversals

### ISSUE THREAD

**Issue by anselb** [mhinojosa24/core-data-structures#7]
- Your binary tree runs well for the most part, but I had some problems with your traversals. First, your `items_pre_order` method seems like it was deleted. Your pre_order search methods seem to work, but I can't test them without the `items_pre_order` method to call. Second, your level order traversal seems to always return an empty list. Your syntax looks good for the most part, but where are you starting? You have `start_node`, but it doesn't seem to be used anywhere. Finally, your `_traverse_in_order_recursive` seems like it was deleted as well. You still have your `items_in_order` method, but it can't work without the other method.

**Comment by mhinojosa24** [comment]
Thanks for the feedback, I really appreciate it. I noticed that I was trying to get rid the todo comments a which I might have deleted a lot my code in process since it was late. Luckily i managed to implemented my missing functions. All test cases are now passing. Thank you :)
